[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "DilateRefinement"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.3.5,<5"
scipy = ">=1.15.1,<2"
numpy = ">=2.2.3,<3"
matplotlib = ">=3.10.0,<4"
